spring:
  application:
    name: ccrm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mauths?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialSize: 5    # 初始化大小
    minIdle: 5        # 最小
    maxActive: 200     # 最大
    maxWait: 60000    # 获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true                    # 打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
    filters: stat,wall,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 30
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    connectionProperties: config.decrypt=false


  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

  freemarker:
      template-loader-path: classpath:/templates/
      charset: utf-8
      suffix: .ftl
      request-context-attribute: request

#jpa配置
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: true
  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 9888
logging:
  file: ./log/${spring.application.name}.log






