package cn.mauth.ccrm.core.domain.set;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 1、商品信息表
 * 2、套餐表公用
 * 3、单独的管理实体
 * 4、销售员查询添加附加通知单选择套餐或商品
 * 5、物流部添加装饰应用
 * Product generated by hbm2java
 */
@Entity
public class SetProduct implements Serializable {
	public static final Integer TYPEPRODCUT=1; 
	public static final Integer TYPEPACKAGE=2; 
	public static final Integer STOCKSTATUSCOMM=1; 
	public static final Integer STOCKSTATUSMAX=2; 
	public static final Integer STOCKSTATUSMIN=3; 
	//商品启用状态
	public static final Integer STOPCOMM=1; 
	public static final Integer STOPYEAS=2;

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer dbid;
	//产品品类型
	@ManyToOne
	@JoinColumn(name = "product_category_id")
	private SetProductCategory productcategory;
	//编码
	private String sn;
	//名称
	private String name;
	//价格
	private BigDecimal price;
	//折扣
	private Float discount;
	//单位
	private String unit;
	//规格
	private String specification;
	//提成金额
	private Float commissionNum;
	//赠送积分
	private Integer givePoint;
	//支持会员卡打折
	private Integer  memberDistStatus;
	//备注
	private String note;
	//拼音
	private String pingyin;
	//商家ID
	private Integer enterpriseId;
	@Column(columnDefinition = "datetime")
	private Date createTime;
	@Column(columnDefinition = "datetime")
	private Date modifyTime;

	//标示数据为商品还是套餐1为商品，2为套餐
	private Integer type;
	//商品停用状态：2、为停用，1、为启用
	private Integer stopStatus;
	private Integer orderNum;
	private String enterpriseIds;
	private Integer useStatus;
	public SetProduct() {
	}

	public SetProduct(Integer dbid) {
		this.dbid = dbid;
	}

	public SetProduct(int dbid, SetProductCategory productcategory, String sn,
					  String name, Integer brandId, Double price, Double costPrice,
					  Float discount, String unit, String specification, Boolean isStock,
					  Boolean isTrack, Integer trackTimeLong, Integer stockNum,
					  Boolean isDeductPercentage, Float deductPercert, Boolean isGift,
					  Integer deductionScore, String note) {
		this.dbid = dbid;
		this.productcategory = productcategory;
		this.sn = sn;
		this.name = name;
		this.discount = discount;
		this.unit = unit;
		this.specification = specification;
		this.givePoint = deductionScore;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public SetProductCategory getProductcategory() {
		return this.productcategory;
	}

	public void setProductcategory(SetProductCategory productcategory) {
		this.productcategory = productcategory;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}



	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}


	public Float getDiscount() {
		return this.discount;
	}

	public void setDiscount(Float discount) {
		this.discount = discount;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getSpecification() {
		return this.specification;
	}

	public void setSpecification(String specification) {
		this.specification = specification;
	}


	public Integer getGivePoint() {
		return givePoint;
	}

	public void setGivePoint(Integer givePoint) {
		this.givePoint = givePoint;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}


	public String getPingyin() {
		return pingyin;
	}

	public void setPingyin(String pingyin) {
		this.pingyin = pingyin;
	}



	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getStopStatus() {
		return stopStatus;
	}

	public void setStopStatus(Integer stopStatus) {
		this.stopStatus = stopStatus;
	}


	public String getEnterpriseIds() {
		return enterpriseIds;
	}

	public void setEnterpriseIds(String enterpriseIds) {
		this.enterpriseIds = enterpriseIds;
	}

	public Float getCommissionNum() {
		return commissionNum;
	}

	public void setCommissionNum(Float commissionNum) {
		this.commissionNum = commissionNum;
	}

	public Integer getMemberDistStatus() {
		return memberDistStatus;
	}

	public void setMemberDistStatus(Integer memberDistStatus) {
		this.memberDistStatus = memberDistStatus;
	}

	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getUseStatus() {
		return useStatus;
	}

	public void setUseStatus(Integer useStatus) {
		this.useStatus = useStatus;
	}

	

}
